name: Build & Release

on:
  push:
    tags:
      - 'v*'  # Triggert bei z. B. v0.1.0

permissions:
  contents: write  # notwendig für Upload zu Releases

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set Version
        id: set_version
        run: echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          EXT=""
          [ "$GOOS" = "windows" ] && EXT=".exe"
          BIN_NAME=pastezero${EXT}
          OUT_DIR=pastezero-${{ steps.set_version.outputs.version }}-${GOOS}-${GOARCH}
          mkdir -p $OUT_DIR
          go build -ldflags "-X main.version=${{ steps.set_version.outputs.version }}" -o $OUT_DIR/$BIN_NAME main.go
          cd $OUT_DIR
          if [ "$GOOS" = "windows" ]; then
            zip -r ../$OUT_DIR.zip .
          else
            tar -czf ../$OUT_DIR.tar.gz .
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            *.zip
            *.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.*
          token: ${{ secrets.GITHUB_TOKEN }}
